  #Author: Ajith Sampath
  #Affiliation: University of Geneva
  # Configuration file for BEACH

  # Telescope parameters
  Telescope_name: "Hirax"  # "Hirax" is the only supported option currently. This sets the aperture diameter and frequency range.
  frequency: 420  # frequency channel to fit in MHz
  aperture_diameter: 6.0   # aperture diameter in meters, default for Hirax is 6m

  # Data parameters
  data_dir: "data"
  datafile: "samplecube_cart.npz"  # path to the input data file (FITS, HDF5, NPY, NPZ, or TXT format)
  normalize_data: True     # whether to normalize the data before fitting
  coord_type: 'auto'        # type of coordinate system the data is in. Options are "cartesian", "polar" or "auto"8
  
  #Gaussian Fit paramters
  gaussian_error_type: "uniform"      # type of error to use in Gaussian fitting, options are "uniform" or "proportional"
  init_gparams: [1.0, 1.0, 1.0,0,0,0]  # Initial guess for Gaussian fit parameters [Amplitude, sigx, sigy, xoffset, yoffset, tilt]
  gminimize_method: "Nelder-Mead"  # minimization method for Gaussian fit, options are "L-BFGS-B", "Nelder-Mead", "Powell", etc.
  gtol: 1e-6               # tolerance for termination of the Gaussian minimization algorithm
  gverbose: True           # whether to print detailed logs during Gaussian fitting

  zernike_error_type: "proportional"       # type of error to use in Zernike fitting, options are "uniform", "proportional", or "custom"
  N: 1500                    # number of Zernike polynomials to fit, default is 15
  skip_minimise: True
  fac: 2.5              #factor to change Gaussian sigma to ZT scaling parameter
  ztminimize_method: "Nelder-Mead"  # minimization method, options are "L-BFGS-B", "Nelder-Mead", "Powell", etc.
  ztmaxiter: 10           # maximum number of iterations for the Zernike minimization algorithm
  zttol: 1e-6               # tolerance for termination of the Zernike minimization algorithm
  zverbose: False           # whether to print detailed logs during fitting

  #plotting paramters
  plot_results: True      # whether to plot the fitting results
  plot_format: ".png"      # format for saving plots, options are "png", "pdf", etc.
  plot_directory: "outputs" # directory to save plots

  #save full coefficients
  save_coef: True
  out_coef_dir: "outputs"
  out_coef_filename: "Coef_full.csv"
  # Output parameters
  save_outputs: True        # whether to save the fitting results to a file
  output_dir : "outputs"
  output_filename: "testbeam"  # output file name
  output_format: ".npz"      # output file format, options are "hdf5" or "npy"

  # Reduce coeff by ranking/removing non-contributing modes
  reduce_coef: True
  in_coef_dir: "outputs"
  in_coef_filename: "Coef_full.csv"
