  # Configuration file for BEACH

  # Telescope parameters
  Telescope_name: "Hirax"  # "Hirax" is the only supported option currently. This sets the aperture diameter and frequency range.
  frequency: 400  # frequency channel to fit in MHz
  aperture_diameter: 6.0   # aperture diameter in meters, default for Hirax is 6m

  # Data parameters
  datafile: "/Users/ajithsampath/SwissPostdoc/samplecube.npz"  # path to the input data file (FITS, HDF5, NPY, NPZ, or TXT format)
  normalize_data: True     # whether to normalize the data before fitting
  coord_type: 'auto'        # type of coordinate system the data is in. Options are "cartesian", "polar" or "auto"
  gaussian_error_type: "uniform"      # type of error to use in Gaussian fitting, options are "uniform" or "proportional"
  init_gparams: [1.0, 1.0, 1.0,0,0,0]  # Initial guess for Gaussian fit parameters [Amplitude, sigx, sigy, xoffset, yoffset, tilt]
  gminimize_method: "Nelder-Mead"  # minimization method for Gaussian fit, options are "L-BFGS-B", "Nelder-Mead", "Powell", etc.
  gtol: 1e-6               # tolerance for termination of the Gaussian minimization algorithm
  gverbose: True           # whether to print detailed logs during Gaussian fitting

  zernike_error_type: "proportional"       # type of error to use in Zernike fitting, options are "uniform", "proportional", or "custom"
  N: 900                    # number of Zernike polynomials to fit, default is 15
  skip_minimise: True
  ztminimize_method: "Nelder-Mead"  # minimization method, options are "L-BFGS-B", "Nelder-Mead", "Powell", etc.
  ztmaxiter: 10           # maximum number of iterations for the Zernike minimization algorithm
  zttol: 1e-6               # tolerance for termination of the Zernike minimization algorithm
  zverbose: False           # whether to print detailed logs during fitting

  plot_results: True      # whether to plot the fitting results
  plot_format: ".png"      # format for saving plots, options are "png", "pdf", etc.
  plot_directory: "plots" # directory to save plots


  # Output parameters
  save_outputs: True        # whether to save the fitting results to a file
  output_filename: "testbeam"  # output file name
  output_format: ".npy"      # output file format, options are "hdf5" or "npy"
  save_intermediate: True     # whether to save intermediate results

  # Gaussian model parameters
  use_gaussian_model: False  # whether to use a Gaussian model for the beam instead of Zernike polynomials
  gaussian_lamdabyD_coef: 1.03         # Coefficient for lambda/D to set the FWHM of the Gaussian beam
  gaussian_amp: 1.0          # Amplitude of the Gaussian beam
  gaussian_offset_x: 0.0   # x offset of the Gaussian beam
  gaussian_offset_y: 0.0   # y offset of the Gaussian beam
  gaussian_rotation: 0.0     # rotation angle of the Gaussian beam in degrees
  gaussian_amp_offset: 0.0       # Amplitude offset of the Gaussian beam
  gaussian_noise: 0.0        # noise level to add to the Gaussian beam
  gaussian_noise_type: "normal" # type of noise to add, options are "normal" or "uniform"
  gaussian_random_seed: 42   # random seed for noise generation

  #Zernike model parameters
  use_zernike_model: True  # whether to use Zernike polynomials for the beam
  dtype: float64    # numpy data type for array, use float128 if supported
  zernike_normalization: True  # normalization for Zernike coefficients, options are True or False
  zernike_noise: 0.0  # noise level to add to Zernike model
  zernike_noise_type: "normal" # type of noise to add, options are "normal" or "uniform"
  zernike_random_seed: 42  # random seed for noise generation 
